"""Database-- Project table --- added start_date and end_date

Revision ID: a356eac807a1
Revises: e39fbd280358
Create Date: 2024-08-02 08:56:53.091144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a356eac807a1'
down_revision: Union[str, None] = 'e39fbd280358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('projects', sa.Column('end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'end_date')
    op.drop_column('projects', 'start_date')
    # ### end Alembic commands ###
