"""added fullname in the table.

Revision ID: a42334ba190f
Revises: 0522e1f0374a
Create Date: 2024-07-24 10:50:20.252873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a42334ba190f'
down_revision: Union[str, None] = '0522e1f0374a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('fullname', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'fullname')
    # ### end Alembic commands ###
