"""deleted fullname in the table.

Revision ID: cc48044d47ba
Revises: a42334ba190f
Create Date: 2024-07-24 10:50:41.530277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc48044d47ba'
down_revision: Union[str, None] = 'a42334ba190f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('fullname', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
